
stages:
  - build

variables:
  IMAGE_NAME: $NEXUS_REGISTRY/ia-cerebro

build-and-push:
  stage: build

  before_script:
    - docker login -u $NEXUS_USER -p $NEXUS_PASSWORD $NEXUS_REGISTRY
    - mkdir -p docker/certs
    - |
      curl --fail --silent --show-error \
        --header "X-Vault-Token: $VAULT_TOKEN" \
        "$VAULT_URL/v1/certificates/data/wildcard-t-systems" \
        | jq -er '.data.data.ca' \
        > docker/certs/t-systems-ca.crt
    - test -s docker/certs/t-systems-ca.crt
    - grep -q -- "-----BEGIN CERTIFICATE-----" docker/certs/t-systems-ca.crt

  script:
    - docker build -f docker/Dockerfile --tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA -t $IMAGE_NAME:latest --no-cache --build-arg PIP_INDEX_URL=https://nexustc.t-systems.es/repository/python-group/simple/ --build-arg PIP_TRUSTED_HOST=nexustc.t-systems.es --build-arg HTTP_PROXY=http://14.10.73.85:8080 --build-arg HTTPS_PROXY=http://14.10.73.85:8080 --build-arg NO_PROXY=nexustc.t-systems.es,registrytc.t-systems.es .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_NAME:latest
    - docker rmi $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:latest

  after_script:
    - rm -f docker/certs
    - docker logout $NEXUS_REGISTRY

  only:
    - main
