services:

  vllm:
    image: public.ecr.aws/q9t5s3a7/vllm-cpu-release-repo:latest
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models:ro
    environment:
      VLLM_CPU_KVCACHE_SPACE: 8
      HF_HUB_OFFLINE: "1"
      TRANSFORMERS_OFFLINE: "1"
      HF_DATASETS_OFFLINE: "1"
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
      http_proxy: ${HTTP_PROXY}
      https_proxy: ${HTTPS_PROXY}
      no_proxy: ${NO_PROXY}
    command: >
      /models/TinyLlama-1.1B-Chat-v1.0
      --host 0.0.0.0
      --port 8000
    networks:
      - ai-network
    restart: unless-stopped