version: '3.8'

services:

  librechat:
    image: ghcr.io/danny-avila/librechat:latest
    ports:
      - "3080:3080"
    environment:
      HOST: ${LIBRECHAT_HOST}
      PORT: ${LIBRECHAT_PORT}
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      ALLOW_EMAIL_LOGIN: ${ALLOW_EMAIL_LOGIN}
      ALLOW_REGISTRATION: ${ALLOW_REGISTRATION}
      RAG_API_URL: ${RAG_API_URL}
      NODE_OPTIONS: ${NODE_OPTIONS}
    volumes:
      - librechat_images:/app/client/public/images
      - ./librechat/librechat.yaml:/app/librechat.yaml
    networks:
      - ai-network
      - traefik
    deploy:
      restart_policy:
        condition: any
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.middlewares.${APP_NAME}-redirect-websecure.redirectscheme.scheme=https
        - traefik.http.routers.${APP_NAME}-web.middlewares=${APP_NAME}-redirect-websecure
        - traefik.http.routers.${APP_NAME}-web.rule=Host(`${APP_HOST}`)
        - traefik.http.routers.${APP_NAME}-web.entrypoints=web
        - traefik.http.routers.${APP_NAME}-websecure.rule=Host(`${APP_HOST}`)
        - traefik.http.routers.${APP_NAME}-websecure.tls=true
        - traefik.http.routers.${APP_NAME}-websecure.entrypoints=websecure
        - traefik.http.services.${APP_NAME}-websecure.loadbalancer.server.port=3080


#  langfuse-web:
#    image: langfuse/langfuse:3
#    ports:
#      - "3000:3000"
#    environment:
#      - DATABASE_URL=postgresql://langfuse:${LANGFUSE_PG_PASSWORD}@${BACKEND_HOST}:5432/langfuse
#      - NEXTAUTH_SECRET=${LANGFUSE_NEXTAUTH_SECRET}
#      - NEXTAUTH_URL=http://${FRONTEND_HOST}:3000
#      - SALT=${LANGFUSE_SALT}
#      - ENCRYPTION_KEY=${LANGFUSE_ENCRYPTION_KEY}
#      - CLICKHOUSE_URL=http://${BACKEND_HOST}:8123
#      #- CLICKHOUSE_URL=clickhouse://langfuse-clickhouse:9000
#      - REDIS_HOST=${BACKEND_HOST}
#      - REDIS_PORT=6379
#      - REDIS_AUTH=
#      - LANGFUSE_S3_EVENT_UPLOAD_BUCKET=langfuse
#      - LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT=http://${BACKEND_HOST}:9000
#      - LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID=minio
#      - LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=${MINIO_PASSWORD}
#      - LANGFUSE_S3_EVENT_UPLOAD_REGION=us-east-1
#      - LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE=true
#      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
#      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
#      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
#      # CLICKHOUSE_MIGRATION_URL=http://langfuse-clickhouse:8123
#      - CLICKHOUSE_MIGRATION_URL=clickhouse://${CLICKHOUSE_USER}:${CLICKHOUSE_PASSWORD}@${BACKEND_HOST}:9002/${CLICKHOUSE_DATABASE}
#      - CLICKHOUSE_CLUSTER_ENABLED=false
#    networks:
#      - langfuse-network
#    healthcheck:
#      test: [ "CMD-SHELL", "wget --spider -q http://$(hostname):3000/api/public/health || exit 1" ]
#      interval: 15s
#      timeout: 10s
#      retries: 5
#      start_period: 100s
#    deploy:
#      restart_policy:
#        condition: any

volumes:
  librechat_images:

networks:
#  langfuse-network:
#    driver: overlay
  ai-network:
    driver: overlay
  traefik:
    external: true