version: '3.8'

services:

  librechat:
    image: ghcr.io/danny-avila/librechat:latest
    environment:
      HOST: ${LIBRECHAT_HOST}
      PORT: ${LIBRECHAT_PORT}
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      ALLOW_EMAIL_LOGIN: ${ALLOW_EMAIL_LOGIN}
      ALLOW_REGISTRATION: ${ALLOW_REGISTRATION}
      RAG_API_URL: ${RAG_API_URL}
      NODE_OPTIONS: ${NODE_OPTIONS}
      ADMIN_PANEL_URL: "https://${LIBRECHAT_APP_HOST}/admin"
    volumes:
      - librechat_images:/app/client/public/images
      - ./librechat/librechat.yaml:/app/librechat.yaml
      # - ./librechat/sonar_logo.svg:/app/client/dist/assets/sonar_logo.svg // De momento no funciona, esperamos versiones futuras
    networks:
      - ai-network
      - traefik
    deploy:
      restart_policy:
        condition: any
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.middlewares.${LIBRECHAT_APP_NAME}-redirect-websecure.redirectscheme.scheme=https"
        - "traefik.http.routers.${LIBRECHAT_APP_NAME}-web.middlewares=${LIBRECHAT_APP_NAME}-redirect-websecure"
        - "traefik.http.routers.${LIBRECHAT_APP_NAME}-web.rule=Host(`${LIBRECHAT_APP_HOST}`)"
        - "traefik.http.routers.${LIBRECHAT_APP_NAME}-web.entrypoints=web"
        - "traefik.http.routers.${LIBRECHAT_APP_NAME}-web.priority=1"
        - "traefik.http.routers.${LIBRECHAT_APP_NAME}-websecure.rule=Host(`${LIBRECHAT_APP_HOST}`)"
        - "traefik.http.routers.${LIBRECHAT_APP_NAME}-websecure.tls=true"
        - "traefik.http.routers.${LIBRECHAT_APP_NAME}-websecure.entrypoints=websecure"
        - "traefik.http.routers.${LIBRECHAT_APP_NAME}-websecure.priority=1"
        - "traefik.http.services.${LIBRECHAT_APP_NAME}-websecure.loadbalancer.server.port=3080"

  librechat-admin-panel:
    image: ghcr.io/clickhouse/librechat-admin-panel:latest
    environment:
      VITE_API_BASE_URL: "https://${LIBRECHAT_APP_HOST}"
      SESSION_SECRET: ${ADMIN_PANEL_SESSION_SECRET}
      SESSION_COOKIE_SECURE: ${SESSION_COOKIE_SECURE}
      TRUST_PROXY: "true"
      API_SERVER_URL: "http://librechat:3080"
      VITE_BASE_PATH: "/admin"
    networks:
      - ai-network
      - traefik
    deploy:
      restart_policy:
        condition: any
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.${LIBRECHAT_ADMIN_NAME}-websecure.rule=Host(`${LIBRECHAT_APP_HOST}`) && (PathPrefix(`/admin/`) || Path(`/admin`))"
        - "traefik.http.routers.${LIBRECHAT_ADMIN_NAME}-websecure.tls=true"
        - "traefik.http.routers.${LIBRECHAT_ADMIN_NAME}-websecure.entrypoints=websecure"
        - "traefik.http.routers.${LIBRECHAT_ADMIN_NAME}-websecure.priority=10"
        - "traefik.http.routers.${LIBRECHAT_ADMIN_NAME}-websecure.service=${LIBRECHAT_ADMIN_NAME}-websecure"
        - "traefik.http.services.${LIBRECHAT_ADMIN_NAME}-websecure.loadbalancer.server.port=3000"

  langfuse-web:
    image: langfuse/langfuse:3
    environment:
      - HOSTNAME=${LANGFUSE_HOST}
      - DATABASE_URL=postgresql://langfuse:${LANGFUSE_PG_PASSWORD}@${BACKEND_HOST}:5432/langfuse
      - NEXTAUTH_SECRET=${LANGFUSE_NEXTAUTH_SECRET}
      - NEXTAUTH_URL=https://${LANGFUSE_APP_HOST}
      - SALT=${LANGFUSE_SALT}
      - ENCRYPTION_KEY=${LANGFUSE_ENCRYPTION_KEY}
      - CLICKHOUSE_URL=http://${BACKEND_HOST}:8123
      - REDIS_HOST=${BACKEND_HOST}
      - REDIS_PORT=6379
      - REDIS_AUTH=
      - LANGFUSE_S3_EVENT_UPLOAD_BUCKET=langfuse
      - LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT=http://${BACKEND_HOST}:9060
      - LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID=minio
      - LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=${MINIO_PASSWORD}
      - LANGFUSE_S3_EVENT_UPLOAD_REGION=us-east-1
      - LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE=true
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_MIGRATION_URL=clickhouse://${CLICKHOUSE_USER}:${CLICKHOUSE_PASSWORD}@${BACKEND_HOST}:9062/${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_CLUSTER_ENABLED=false
      - LANGFUSE_INIT_ORG_ID=ia-interna
      - LANGFUSE_INIT_ORG_NAME=IA INTERNA
      - LANGFUSE_INIT_USER_EMAIL=${LANGFUSE_USER_EMAIL}
      - LANGFUSE_INIT_USER_NAME=${LANGFUSE_USER}
      - LANGFUSE_INIT_USER_PASSWORD=${LANGFUSE_USER_PASSWORD}
      - AUTH_DISABLE_SIGNUP=true
    networks:
      - langfuse-network
      - traefik
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://$$(hostname):3000/api/public/health || exit 1" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 100s
    deploy:
      restart_policy:
        condition: any
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.middlewares.${LANGFUSE_APP_NAME}-redirect-websecure.redirectscheme.scheme=https"
        - "traefik.http.routers.${LANGFUSE_APP_NAME}-web.middlewares=${LANGFUSE_APP_NAME}-redirect-websecure"
        - "traefik.http.routers.${LANGFUSE_APP_NAME}-web.rule=Host(`${LANGFUSE_APP_HOST}`)"
        - "traefik.http.routers.${LANGFUSE_APP_NAME}-web.entrypoints=web"
        - "traefik.http.routers.${LANGFUSE_APP_NAME}-websecure.rule=Host(`${LANGFUSE_APP_HOST}`)"
        - "traefik.http.routers.${LANGFUSE_APP_NAME}-websecure.tls=true"
        - "traefik.http.routers.${LANGFUSE_APP_NAME}-websecure.entrypoints=websecure"
        - "traefik.http.services.${LANGFUSE_APP_NAME}-websecure.loadbalancer.server.port=3000"
        - "traefik.http.routers.langfuse-web.service=langfuse-websecure"
        - "traefik.http.routers.langfuse-websecure.service=langfuse-websecure"

volumes:
  librechat_images:

networks:
  langfuse-network:
    driver: overlay
  ai-network:
    driver: overlay
  traefik:
    external: true