services:
  librechat:
    image: ghcr.io/danny-avila/librechat:latest
    ports:
      - "${LIBRECHAT_PORT:-3080}:${LIBRECHAT_PORT:-3080}"
    environment:
      HOST: ${LIBRECHAT_HOST:-0.0.0.0}
      PORT: ${LIBRECHAT_PORT:-3080}
      SESSION_COOKIE_SECURE: "false"
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      ALLOW_EMAIL_LOGIN: ${ALLOW_EMAIL_LOGIN}
      ALLOW_REGISTRATION: ${ALLOW_REGISTRATION}
      RAG_API_URL: ${RAG_API_URL}
      NODE_OPTIONS: ${NODE_OPTIONS}
      ADMIN_PANEL_URL: "http://localhost:3000"
    volumes:
      - librechat_images:/app/client/public/images
      - ./librechat/librechat.yaml:/app/librechat.yaml
    networks:
      - ai-network

  librechat-admin-panel:
    image: ghcr.io/clickhouse/librechat-admin-panel:latest
    ports:
      - "3000:3000"
    environment:
      VITE_API_BASE_URL: "http://librechat:${LIBRECHAT_PORT:-3080}"
      SESSION_SECRET: ${ADMIN_PANEL_SESSION_SECRET}
      SESSION_COOKIE_SECURE: "false"
      API_SERVER_URL: "http://librechat:3080"
    networks:
      - ai-network

  librechat-mongodb:
    image: mongo:7
    volumes:
      - mongo_data_dev:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    command: >
      mongod
      --wiredTigerCacheSizeGB 4
      --bind_ip_all
    networks:
      - ai-network
    deploy:
      restart_policy:
        condition: any

volumes:
  librechat_images:
  mongo_data_dev:

networks:
  ai-network: