---
- name: Deploy ia-backend stack
  hosts: dtz_srv_vmwz874,dtz_srv_vmwz919
  become: true
  gather_facts: false

  tasks:

    - name: test
      shell: >
        whoami

    - name: test
      shell: >
        ls -la /data/docker/stacks/internal-ia